### PR TITLE
allow to set the config file from a define

### PR DESCRIPTION
**Pull request by zelurker**
warning the quotes must be escaped :
gcc -DMUSASHI_CNF=\"myconf.h\" ...

It's to allow to include musashi as a git submodule in a project. This allows you to change you config file as you want while keeping the project's makefile separated.
If you don't pass any MUSASHI_CNF define then of course the default config file is included.

### CODE REVIEW

**Comment by zelurker** [comment]
And I just noticed the antislash was eaten, it should have been :
gcc -DMUSASHI_CNF=\"myconf.h\" ...

**Comment by zelurker** [comment]
Well it eats \ all the time, just assume there are \ (antislashes) before the "

**Comment by kstenerud** [comment]
Actually, I think you can do this:

```c
#include #MUSASHI_CNF
```

And then the preprocessor will surround it with quotes. Try that and if it works please update the PR :)

**Comment by zelurker** [comment]
No it fails, but it's not a big deal, I had included the warning about the
quotes in the git comment, once you know it it's ok.
Found the info on the web, 1st time I need to include a file from a define !
source/Musashi/m68k.h:52:10: erreur: #include attend "NOM_DE_FICHIER" ou
<NOM_DE_FICHIER>
   52 | #include #MUSASHI_CNF

Le mer. 6 nov. 2019 à 20:21, Karl Stenerud <notifications@github.com> a
écrit :

**Comment by zelurker** [comment]
Oh well, I wanted to post just my latest commit about moving the read/write functions to the cpu "context", but github insists on sending the whole thing, so here it is.
I don't think you'll want to merge this anyway, that's not a problem I work on the fork I have, so it's more for info.
The idea behind this is to use musashi to emulate 2 asm cpu emulators, one for the 68020, the other for the 68000 for when it's unconvenient to have some asm (in 64 bits or with a non intel architecture). It's for raine. That's done, everything is working fine now, tested taito f3 (68020 + 68000 together), cps2 encryption (neat implementation with just the immediate reads to assign), everything seems fine now.
On the patch itself, finally I kept the old default names, I tried to make a patch whcih make as little changes as possible, and it works fine like that. It means that if you enable SEPARATE_READS, then you must assign something to m68ki_cpu.read_im16 and so on, otherwise it's assigned the default read functions by default to avoid a crash and it will do nothing special.
Changed the doc to say that, also you had a refence to M68K_SEPARATE_IMM in the readme, which doesn't exist...
Anyway thanks for musashi as it is, very useful ! :)

**Comment by faybs** [comment]
Just wanted to chime in... I've tried zelurker's first commit in VS2019, and in there you must *not* use backslashes. I'm guessing those are needed for either Make or gcc. In my VS2019 project I added the following to my Preprocessor Definitions and it works:

`MUSASHI_CNF="$(ProjectDir)Machine/musashi_cnf.h"`

**Comment by zelurker** [comment]
Yes it's because of the shell in unix actually, if you don't have any
shell, you don't need the backslashes.

Le dim. 17 nov. 2019 à 05:10, Fabian Nunez <notifications@github.com> a
écrit :

**Comment by faybs** [comment]
Thanks. Then I would argue that quote handling is specific to your dev environment, and so it's a documentation issue. Ship it :)

**Comment by zelurker** [comment]
You mean adding that as a comment to the source ? well at this rate the
comment will be longer than the code itself, plus it took me less than 1
minute to find on the web how to make it work... but I can do it, no
problem, someone else wants that in the code ?

Le dim. 17 nov. 2019 à 20:43, Fabian Nunez <notifications@github.com> a
écrit :

**Comment by faybs** [comment]
No, just in the readme. In the same paragraph where you describe what MUSASHI_CNF does, mention that when using unix-like shells (Linux, maybe cygwin too?) needs to escape the quotes, and in places like msbuild and Visual Studio one must not.

**Comment by zelurker** [comment]
Well the trick is that nobody added anything about that in the readme... oh well I had a minute so I added something and pushed to git. Normally the commit appears here automatically without doing anything. Now the problem is that all my recent commits are together even if they are not about the same thing...

**Comment by faybs** [comment]
That's why the usual advice is that one should stick to one bugfix or feature per pull request... I think the only options you have are to push another commit to this 
PR that undoes the second one with the other fixes, or cancel this pull request and create a new one.

**Comment by zelurker** [comment]
Actually I didn't want to push the 2nd commit, I tried to create a new pull
request, but github wanted to merge it with the 1st one and didn't want to
do it otherwise.
Now it's messy, well I hope Karl can select just the commits he wants,
otherwise he can just cancel this one, and I'll try that again later...

Le lun. 18 nov. 2019 à 19:20, Fabian Nunez <notifications@github.com> a
écrit :

**Comment by kstenerud** [comment]
Unfortunately, github makes this all-or-nothing :/

If you create a different named branch, it should allow you to do just the parts you intended though.

**Pull request closed without merging**
