### PR TITLE
implemented some more fpu instructions

### PR DESCRIPTION
**Pull request by bebbo**
feel free to mention me somewhere/somehow^^

### CODE REVIEW

**Comment by michalsc** [comment]
The constants 0x30 and 0x31 of FMOVECR are wrong. At 0x30 there should be Ln(2), at 0x31 there is Ln(10).

However, I do understand the reason of the mistake. The original documents are of bad quality and some of them are OCR-ed with several severe mistakes.

**Comment by kstenerud** [comment]
Wow! This is great! Please fix the small issues mentioned, and also maybe we should put in a "special thanks" or CONTRIBUTORS.md document where credit can be given?

**Comment by bebbo** [comment]
> 
> 
> The constants 0x30 and 0x31 of FMOVECR are wrong. At 0x30 there should be Ln(2) = M_LN2, at 0x31 there is Ln(10) = M_LN10.
> 
> However, I do understand the reason of the mistake. The original documents are of bad quality and some of them are OCR-ed with several severe mistakes.

thanks - I guessed .... wrong :-)

**Comment by bebbo** [comment]
> 
> 
> MOVECR again:
> 
>     1. The constants 0x3c-0x3f exceed the exponent range available for double data type and thus should be either defined as +INF or maximal allowed positive number. The code in current form throws warning on error depending on compiler flags.


maybe the internal representation will be changed to long double - I can live with these warnings for now.

>     2. Constants other than those officially defined are not illegal, therefore fatalerror with unknown offset is a little bit too restrictive. Instead some random value or, preferably, 0.0 should be returned in the default: statement:
>        default: source = 0.0;


I disagree: thanks to the fatal errors you can catch a missing implementation where it occurs. Otherwise you get wrong results and have to research why it's wrong.

**Comment by michalsc** [comment]
> I disagree: thanks to the fatal errors you can catch a missing implementation where it occurs. Otherwise you get wrong results and have to research why it's wrong.

Not in this case. Here you have set of *defined* constants in FPU's ROM. All m68k FPU implementations have the documented constant of exactly the same value but use rest of the entries within the pool either for internal use or return 0.0, as the manual says:

> The on-chip ROM contains other constants useful only to the on- chip microcode rou- tines. The values contained at offsets other than those defined above are reserved for the use of Motorola and may be different on various mask sets of the floating-point coprocessor. These undefined values yield the value 0.0 in the M68040FPSP.

Anyway, fetching a constant not mentioned in manual is fully legal - it is not an undefined behavior.

**Pull request closed without merging**
